name: Print Echo "hi"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  echo_job:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print "hi"
        env:
          MY_NAME: ${{ vars.NAME }}
        run: |
          echo "Hi my name is $MY_NAME"
          
  

