name: Print Echo "hi"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
env:
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  echo_job:
    runs-on: ubuntu-latest
    if: ${{ vars.USE_VARIABLES == 'true' }}
    environment: ${{ vars.ENVIRONMENT_STAGE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print "hi"
        env: 
          MY_NAME: ${{ vars.NAME }}
        run: echo "hi $MY_NAME "

