name: Print Echo "hi"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  echo_job:
    runs-on: ubuntu-latest
    environment: ${{ vars.ENVIRONMENT_STAGE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print "hi"
        env: 
          MY_NAME: ${{ vars.NAME }}
        run: echo "hi $MY_NAME "

