name: Print Echo "hi"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  echo_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print "hi"
        run: echo "hi"

